package locators;

public class Backend_loc {
public final static String USERNAME = "username";
public final static String PASSWORD = "password";
public final static String LOGINBTN = "//*[@id='logininformation']//button[text()='Login']";
public final static String LOGOUTBTN = "logout";
//locators for create new property
public final static String CREATEPROPERTY = "//*[@id='main-content']//a[contains(text(), 'Create New Property')]";
public final static String CRITERIAHEADING = "//*[@id='main-content']//h1[contains(text(), 'Create a Property - Step 1 of 3')]";
public final static String EXECPLUSBUTTON = "package1";
public final static String EXECUTIVEBUTTON = "package2";
public final static String ASSOCIATEBUTTON = "package3";
public final static String SILVERBUTTON = "package4";
//international pacckage locator
public final static String INTERNATIONALBUTTON = "package5";
public final static String CONTINUEBUTTON = "css=input[name='continue']"; 
//Create property page 2 locators
public final static String CREATEPAGE2HEADING = "//*[@id='main-content']//h1[text()='User Info - Step 2 of 3']";
public final static String USERNAMEFIELD = "//*[@id='username']";
public final static String PASSWORDFIELD = "//*[@id='newpassword']";
public final static String FIRSTNAME = "//*[@id='first_name']";
public final static String LASTNAME = "//*[@id='last_name']";
public final static String EMAIL = "//*[@id='emailId']";
public final static String BACKTOSTEP1 = "css=input[name='Back to step1']";
//create property page 3 locators
public final static String CREATEPAGE3HEADING = "//*[@id='main-content']//h1[contains(text(), 'Listing Info - Step 3 of 3')]";
public final static String PROPERTYNAME = "//*[@id='property_name']";
public final static String ADDRESSLINE1 = "//*[@id='address1']";
public final static String ADDRESSLINE2 = "//*[@id='address2']";
public final static String ZIPCODE = "//*[@id='zipcode']";
public final static String CITY = "//*[@id='city']";
public final static String STATE = "//*[@id='state']";
public final static String COUNTRY = "//*[@id='country']";
public final static String PHONENUMBER = "//*[@id='phonenumber']";
public final static String BACTTOSTEP2 = "css=input[name='Back to step2']";
public final static String CREATEACCOUNT = "//*[@id='continue_account']";
public final static String ANYGUESTCARDCOUNT = "//div[contains(@class, 'guestCards')]//p[contains(@class,'reports-medium') and text()='num']";
public final static String GUESTCARDCOUNT = "//div[contains(@class, 'guestCards')]//p[contains(@class,'reports-medium')]";

//Locators for Floor Plan Page
public final static String ADDFLOORPLANBTN = "//*[@id='main-content']//button[contains(text(),'ADD A FLOOR PLAN')]";
public final static String SAVECHANGESBTN = "//*[@id='addfloorplan']//button[contains(text(),'SAVE CHANGES')]";
public final static String FLOORPLANNAME = "floor_name";
public final static String BEDROOMS = "bedrooms";
public final static String BATHROOMS = "bathrooms";
public final static String MINSQFT = "min_sft";
public final static String MAXSQFT = "max_sft";
public final static String MINSTAY = "minimum_stay";
public final static String STARTRATE = "starting_rate";
public final static String STARTRATETYPE = "starting_rate_type";
public final static String DAILYPRICEMIN = "daily_price_min";
public final static String DAILYPRICEMAX= "daily_price_max";
public final static String DAILYPRICECALL = "daily_price_call";
public final static String WEEKLYPRICEMIN = "weekly_price_min";
public final static String WEEKLYPRICEMAX = "weekly_price_max";
public final static String WEEKLYPRICECALL = "weekly_price_call";
public final static String MONTHLYPRICEMIN = "monthly_price_min";
public final static String MONTHLYPRICEMAX = "monthly_price_max";
public final static String RENTALDEPOSIT = "rental_deposit";
public final static String APPFEE = "application_fee";
public final static String LEASETERMS = "lease_terms";
public final static String DESCRIPTION = "description";
public final static String DISPLAYONSITE = "display_on_site";
public final static String SAVEMSG = "//*[@id='errormessage']//div[contains(text(),'Floor plan saved!')]";

//Locators for profile tab
public final static String SITEID = "//*[@id='site_id']";
public final static String EDITBUTTON = "//*[@id='main-content']//a[contains(text(), 'EDIT')]";
public final static String PROPERTNAME = "//*[@id='admin-sections-container']//h1";
public final static String PROPERTYNAMEFIELD = "//*[@id='property_name']";
public final static String ADDRESSL1FIELD = "//*[@id='address']";
public final static String ADDRESSL2FIELD = "//*[@id='address2']";
public final static String ZIPFIELD = "//*[@id='zip']";
public final static String CITYFIELD = "//*[@id='city']";
public final static String STATEFIELD = "//*[@id='state']";
public final static String PHONEFIELD = "//*[@id='phone']";
public final static String EXTFIELD = "//*[@id='ext']";
public final static String FAXFIELD = "//*[@id='fax']";
public final static String WEBADDRESSFIELD = "//*[@id='website_address']";
public final static String VANITYURLFIELD = "//*[@id='vanity_url']";
public final static String PROMOTEXTFIELD = "//*[@id='vanity_url']";
public final static String RADIOBUTTONCONDOS = "//*[@id='profiledetails']/div[5]/div/div[1]/div[3]/div/label";
public final static String HEADLINEFIELD = "//*[@id='headline']";
public final static String TAGLINEFIELD = "//*[@id='tagline']";
public final static String SHORTDESCRIPTION = "//*[@id='short_description']";
public final static String LONGDESCRIPTION = "//*[@id='long_description']";
public final static String BULLETPOINT1 = "//*[@id='bp1']";
public final static String BULLETPOINT2 = "//*[@id='bp2']";
public final static String BULLETPOINT3 = "//*[@id='bp3']";
public final static String BULLETPOINT4 = "//*[@id='bp4']";
public final static String BULLETPOINT5 = "//*[@id='bp5']";
public final static String BULLETPOINT6 = "//*[@id='bp6']";
public final static String BULLETPOINT7 = "//*[@id='bp7']";
public final static String BULLETPOINT8 = "//*[@id='bp8']";
public final static String BULLETPOINT9 = "//*[@id='bp9']";
public final static String BULLETPOINT10 = "//*[@id='bp10']";
public final static String PROFILEPAGECHECK1 = "//*[@id='profile_page_1']";
public final static String PROFILEPAGECHECK2 = "//*[@id='profile_page_2']";
public final static String PROFILEPAGECHECK3 = "//*[@id='profile_page_3']";
public final static String PROFILEPAGECHECK4 = "//*[@id='profile_page_4']";
public final static String PROFILEPAGECHECK5 = "//*[@id='profile_page_5']";
public final static String PROFILEPAGECHECK6 = "//*[@id='profile_page_6']";
public final static String PROFILEPAGECHECK7 = "//*[@id='profile_page_7']";
public final static String PROFILEPAGECHECK8 = "//*[@id='profile_page_8']";
public final static String PROFILEPAGECHECK9 = "//*[@id='profile_page_9']";
public final static String PROFILEPAGECHECK10 = "//*[@id='profile_page_10']";
public final static String SEARCHRESCHECK1 = "//*[@id='search_res_1']";
public final static String SEARCHRESCHECK2 = "//*[@id='search_res_2']";
public final static String SEARCHRESCHECK3 = "//*[@id='search_res_3']";
public final static String SEARCHRESCHECK4 = "//*[@id='search_res_4']";
public final static String SEARCHRESCHECK5 = "//*[@id='search_res_5']";
public final static String SEARCHRESCHECK6 = "//*[@id='search_res_6']";
public final static String SEARCHRESCHECK7 = "//*[@id='search_res_7']";
public final static String SEARCHRESCHECK8 = "//*[@id='search_res_8']";
public final static String SEARCHRESCHECK9 = "//*[@id='search_res_9']";
public final static String SEARCHRESCHECK10 = "//*[@id='search_res_10']";
public final static String PMCNAMEFIELD = "//*[@id='pmc_name']";
public final static String PMCIDFIELD = "//*[@id='pmc_id']";
public final static String PAYMENTVISAMASTERCRD = "[//*[@id='pmc_id']";
public final static String PAYMENTDISCOVER = "//*[@id='paymentmethod2']";
public final static String PAYAMERICANEXP = "//*[@id='paymentmethod3']";
public final static String PAYPAYPAL = "//*[@id='paymentmethod4']";
public final static String PAYPERSONALCHECK = "//*[@id='paymentmethod5']";
public final static String PAYCOMPCHECK = "//*[@id='paymentmethod6']";
public final static String PAYCORPORATEBILL = "//*[@id='paymentmethod7']";
public final static String PAYDINERCLUB = "//*[@id='paymentmethod8']";
public final static String SAVECHANGESBUTTONATBOTTOM = "//*[@id='profiledetails']/div[9]//button[contains(text(), 'SAVE CHANGES')]";
//Save changes message
public final static String SAVECHANGEMSG = "errormessage";
//Locators for Account Details Page
public final static String USERACTIVE_YES = "//*[@id='user_active' and @value=1]";
public final static String USERACTIVE_NO = "//*[@id='user_active' and @value=0]";
public final static String ACCDETAIL_SAVECHANGEBTN = "//*[@id='accountdetails']//div[1]//button[contains(text(),'SAVE CHANGES')]";
public final static String LOGIN_ERROR = "//*[@id='auth_login']//div[contains(text(),'Invalid Username/Password.')]";
//Admin Button
public final static String ADMIN_BTN = "//*[@class='col-md-12']//a[text()='Admin']";
public final static String CREATEUSERADMIN = "//*[@id='addpmc']";
//Create User admin
public final static String CREATEADMIN_USERNAME = "username";
public final static String CREATEADMIN_PASSWORD = "newpassword";
public final static String CREATEADMIN_FIRSTNAME = "first_name";
public final static String CREATEADMIN_LASTNAME = "last_name";
public final static String CREATEADMIN_ACTIVEDROPDWN = "useractive";
public final static String CREATEADMIN_ACCESSLEVEL = "accesslevel";
public final static String CREATEADMIN_SITEID = "site_id";
public final static String CREATEADMIN_SUCCESS = "//*[@id='errormessage']//div[contains(text(),'User Added Successfully.')]";
public final static String CREATEADMIN_SITEID30 = "multiple_site_ids";
//Save button User admin
public final static String SAVE_BTN = "//*[@id='addSave']";
//User Level Login
public final static String UPDATEPASS = "myModalLabel";
public final static String UPDATEPASSNEW = "newupdatepassword";
public final static String UPDATEPASSNEWCONFIRM = "newupdatepasswordconfi";
public final static String UPDATEPASS_SAVEBTN = "//*[@id='userbuttonpasshide']/button[contains(text(),'Save')]";
public final static String UPDATEPASS_MSG = "//*[@id='userbuttonpasshide']/strong[contains(text(),'Password Updated.')]";
//locators for verification of display on website
public final static String ACCOUNTDETAILSTAB = "//*[@id='brearcrumbs-property']/div/div/ul/li[1]/a";
public final static String DISPLAYONWEBSITEYES = "//*[@id='display_on_website']";
public final static String DISPLAYONWEBSITENO = "//*[@id='display_on_website'][@value='0']";
public final static String SHAREH1 = "//*[@id='profile-right']/h2";
public final static String SEARCHBUTTON = "//*[@id='search']";
public final static String SAVECHANGES = "//*[@id='accountdetails']//button[contains(text(), ' SAVE CHANGES')]";
//locators for preview property
public final static String PREVIWPROPERTY = "//*[@id='profiledetails']//a[contains(text(), 'PREVIEW PROPERTY')]";
public final static String FOOTERPREVIEWPAGE = "//*[@id='copyrights']/div/div[2]/div[2]/nav[1]/ul/li[1]/a";
//locators for image upload
public final static String PROPFOUNDH1 = "//*[@id='main-content']//h1";
public final static String EDITBUTTONS = "//*[@id='main-content']//a[contains(text(), 'EDIT')]";
public final static String PMCNAME = "//*[@id='pmc_name']";
public final static String ADSPOTLIGHTH1 = "//*[@id='main-content']/div[1]/div[6]/div/h3";
public final static String BROWSELOGO = "//*[@id='image_logo']";
public final static String BROWSEFEATURED = "//*[@id='image_featured']";
public final static String ADDPHOTOFRLOGO = "//*[@id='gallery-images-top']/div[1]/div//input[@id='upload']";
public final static String ADDPHOTOFORFEATUREDIMG = "//*[@id='gallery-images-top']/div[2]/div//input[@id='upload']";
public final static String IMAGESTAB = "//*[@id='brearcrumbs-property']//a[contains(text(), 'IMAGES')]";
public final static String ADDFILEBTN = "//*[@id='multifile']";
public final static String STARTUPLOAD = "//*[@id='fileupload']/div/div[1]/button[1]";
public final static String SAVEUPLOAD = "//*[@id='pagerefreshdata']";
public final static String cropimagebtn = "//*[@id='featuredModal']/div/div/form/div[3]/input";
//Locators for amenities tab
public final static String amenitiestab = "//*[@id='brearcrumbs-property']//a[contains(text(), 'AMENITIES')]";
public final static String communityfeatureh1 = "//*[@id='profiledetails']//h3";
public final static String amenitiessavebutton = "//*[@id='profiledetails']//button[contains(text(), 'SAVE CHANGES')]";
public final static String Bilingual = "//*[@id='amenities_1']";
public final static String OptionalDropdown = "//[@id='div_amenities_1']";
public final static String optional1 = "//*[@name='opt_amenities_1']";
public final static String BusinessCenter = "//*[@id='amenities_2']";
public final static String optional2 = "//*[@id='optt_amenities_2']";
public final static String ConciergeServices = "//*[@id='amenities_3']";
public final static String optional3 = "//*[@id='optt_amenities_3']";
public final static String ConferenceRooms = "//*[@id='amenities_4']";
public final static String optional4 = "//*[@id='optt_amenities_4']";
public final static String ContinentalBreakfastIncluded = "//*[@id='amenities_5']";
public final static String optional5 = "//*[@id='optt_amenities_5']";
public final static String ControlledAccess = "//*[@id='amenities_6']";
public final static String optional6 = "//*[@id='optt_amenities_6']";
public final static String CoveredParking = "//*[@id='amenities_7']";
public final static String optional7 = "//*[@id='optt_amenities_7']";
public final static String FitnessCenter = "//*[@id='amenities_8']";
public final static String optional8 = "//*[@id='optt_amenities_8']";
public final static String Garages = "//*[@id='amenities_9']";
public final static String optional9 = "//*[@id='optt_amenities_9']";
public final static String GroceryService = "//*[@id='amenities_10']";
public final static String optional10 = "//*[@id='optt_amenities_10']";
public final static String HotBreakfastIncluded = "//*[@id='amenities_11']";
public final static String optional11 = "//*[@id='optt_amenities_11']";
public final static String HotTub = "//*[@id='amenities_12']";
public final static String optional12 = "//*[@id='optt_amenities_12']";
public final static String Housekeeping = "//*[@id='amenities_13']";
public final static String optional13 = "//*[@id='optt_amenities_13']";
public final static String LaundryDryCleaningService = "//*[@id='amenities_14']";
public final static String optional14 = "//*[@id='optt_amenities_14']";
public final static String LaundryRoom = "//*[@id='amenities_15']";
public final static String optional15 = "//*[@id='optt_amenities_15']";
public final static String LessThan1MileFromHighway = "//*[@id='amenities_16']";
public final static String optional16 = "//*[@id='optt_amenities_16']";
public final static String OffsiteGymMembership = "//*[@id='amenities_63']";
public final static String optional63 = "//*[@id='optt_amenities_63']";
public final static String Playground = "//*[@id='amenities_17']";
public final static String optional17 = "//*[@id='optt_amenities_17']";
public final static String PrivateEntry = "//*[@id='amenities_18']";
public final static String optional18 = "//*[@id='optt_amenities_18']";
public final static String RacquetballCourt = "//*[@id='amenities_19']";
public final static String optional19 = "//*[@id='optt_amenities_19']";
public final static String Restaurant = "//*[@id='amenities_20']";
public final static String optional20 = "//*[@id='optt_amenities_20']";
public final static String Sauna = "//*[@id='amenities_21']";
public final static String optional21 = "//*[@id='optt_amenities_21']";
public final static String SocialActivities = "//*[@id='amenities_22']";
public final static String optional22 = "//*[@id='optt_amenities_22']";
public final static String SpaSalon = "//*[@id='amenities_23']";
public final static String optional23 = "//*[@id='optt_amenities_23']";
public final static String Storage = "//*[@id='amenities_24']";
public final static String optional24 = "//*[@id='optt_amenities_24']";
public final static String SwimmingPool = "//*[@id='amenities_25']";
public final static String optional25 = "//*[@id='optt_amenities_25']";
public final static String TennisCourts = "//*[@id='amenities_26']";
public final static String optional26 = "//*[@id='optt_amenities_26']";
public final static String ValetService = "//*[@id='amenities_27']";
public final static String optional27 = "//*[@id='optt_amenities_27']";
public final static String VolleyballCourt = "//*[@id='amenities_28']";
public final static String optional28 = "//*[@id='optt_amenities_28']";
public final static String WalkingDistancetoDining = "//*[@id='amenities_29']";
public final static String optional29 = "//*[@id='optt_amenities_29']";
public final static String WiFiinCommonAreas = "//*[@id='amenities_30']";
public final static String optional30 = "//*[@id='optt_amenities_30']";
//Interior Features
public final static String Coffiemaker = "//*[@id='amenities_31']";
public final static String optional31 = "//*[@id='optt_amenities_31']";
public final static String complementorynewspaper = "//*[@id='amenities_32']";
public final static String optional32 = "//*[@id='optt_amenities_32']";
public final static String disabilityaccess = "//*[@id='amenities_33']";
public final static String optional33 = "//*[@id='optt_amenities_33']";
public final static String Fireplace = "//*[@id='amenities_34']";
public final static String optional34 = "//*[@id='optt_amenities_34']";
public final static String fullyequipedkitchen = "//*[@id='amenities_35']";
public final static String optional35 = "//*[@id='optt_amenities_35']";
public final static String highspeedinternet = "//*[@id='amenities_36']";
public final static String optional36 = "//*[@id='optt_amenities_36']";
public final static String kitchenette = "//*[@id='amenities_37']";
public final static String optional37 = "//*[@id='optt_amenities_37']";
public final static String locaphone = "//*[@id='amenities_38']";
public final static String optional38 = "//*[@id='optt_amenities_38']";
public final static String ondemandrental = "//*[@id='amenities_39']";
public final static String optional39 = "//*[@id='optt_amenities_39']";
public final static String patioorbalconey = "//*[@id='amenities_40']";
public final static String optional40 = "//*[@id='optt_amenities_40']";
public final static String premiumcablechannel = "//*[@id='amenities_41']";
public final static String optional41 = "//*[@id='optt_amenities_41']";
public final static String satellitetv = "//*[@id='amenities_42']";
public final static String optional42 = "//*[@id='optt_amenities_42']";
public final static String suitesavailable = "//*[@id='amenities_43']";
public final static String optional43 = "//*[@id='optt_amenities_43']";
public final static String utilitiespaid = "//*[@id='amenities_44']";
public final static String optional44 = "//*[@id='optt_amenities_44']";
public final static String voicemail = "//*[@id='amenities_45']";
public final static String optional45 = "//*[@id='optt_amenities_45']";
public final static String washerordrier = "//*[@id='amenities_46']";
public final static String optional46 = "//*[@id='optt_amenities_46']";
public final static String wifi = "//*[@id='amenities_47']";
public final static String optional47 = "//*[@id='optt_amenities_47']";
public final static String alarmsystem = "//*[@id='amenities_48']";
public final static String optional48 = "//*[@id='optt_amenities_48']";
public final static String babyfurniture = "//*[@id='amenities_49']";
public final static String optional49 = "//*[@id='optt_amenities_49']";
public final static String dvdplayer = "//*[@id='amenities_50']";
public final static String optional50 = "//*[@id='optt_amenities_50']";
public final static String faxmachine = "//*[@id='amenities_51']"; 
public final static String optional51 = "//*[@id='optt_amenities_51']";
public final static String flatscreentv = "//*[@id='amenities_52']";
public final static String optional52 = "//*[@id='optt_amenities_52']";
public final static String furnishedavailable = "//*[@id='amenities_53']";
public final static String optional53 = "//*[@id='optt_amenities_53']";
public final static String housewares = "//*[@id='amenities_54']";
public final static String optional54 = "//*[@id='optt_amenities_54']";
public final static String microwave = "//*[@id='amenities_55']";
public final static String optional55 = "//*[@id='optt_amenities_55']";
public final static String mp3 = "//*[@id='amenities_56']";
public final static String optional56 = "//*[@id='optt_amenities_56']";
public final static String telivision = "//*[@id='amenities_57']";
public final static String optional57 = "//*[@id='optt_amenities_57']";
public final static String unfurnishedavailable = "//*[@id='amenities_58']";
public final static String optional58 = "//*[@id='optt_amenities_58']";
public final static String catsallowed = "//*[@id='amenities_60']";
public final static String optional60 = "//*[@id='optt_amenities_60']";
public final static String largedogsallowed = "//*[@id='amenities_62']";
public final static String optional62 = "//*[@id='optt_amenities_62']";
public final static String petsallowed = "//*[@id='amenities_59']";
public final static String optional59 = "//*[@id='optt_amenities_59']";
public final static String smalldogsallowed = "//*[@id='amenities_61']";
public final static String optional61 = "//*[@id='optt_amenities_61']";

}